Feature: 글로벌 예외처리 및 HTTP 반환값 설정
Team-Digimon/muzusi-was pull request #10
Opened 2024-12-07 16:29 UTC by hky035

## 배경
- #5 
- 일관된 HTTP 응답을 위한 성공/실패 반환값 설정 

## 작업 사항
- `SuccessResponse`, `SuccessType` 추가
   - HTTP 요청 성공 반환값 : `code`, `message`, `data`(null일 경우 응답에서 제외)
   - HTTP 요청 성공 시 `code` : HTTP status code 사용 예정

- `ErrorResponse`, `ErrorType` 추가
   - HTTP 요청 실패 반환값 : `code`, `message`
   - HTTP 요청 실패 시 `code` : 커스텀 에러 코드 사용(xxxx) 예정
   - 각 기능 별 `ErrorType` enum 클래스 정의 
      - `Common`(0xxx) / `Auth` (1xxx) / `Stock` (2xxx) / `Post` (3xxx)

## 추가 논의
- 커스텀 에러 코드 관련
**HTTP status code(xxx) + Reason code(x)** → **기능 구분 code (x) + Reason code(xxx)**
: 사전 논의 시 전자 방식으로 논의했었지만, 기능 별 에러 코드 정의 시 코드 수가 부족할 것으로 예상되어 후자로 변경하여 구현하였습니다.

2024-12-07 17:00 UTC, DaeYoung0726 requested changes
고생하셨습니다!
몇 가지 의견과 다른 방향의 에러 로그 출력에 대해서 코멘트 남기겠습니다!

2024-12-07 17:00 UTC, DaeYoung0726 commented on src/main/java/muzusi/global/response/error/type/CommonErrorType.java
> +public enum CommonErrorType implements BaseErrorType {
`CommonErrorType`과 같이 공통적으로 사용되는 것은 해당 패키지 위치가 적절하다고 생각합니다!

하지만, User, Post, Stock 등 도메인에 해당하는 예외처리는 도메인 별로 두는건 어떻게 생각하시나요??
ex) `entity/user/exception`

전체 예외 처리를 관리하는 측면을 생각한다면 기영님이 작성하신 부분이 괜찮다고 생각이 들고,
도메인에 해당하는 예외 처리를 관리하는 측면에서는 제가 의견드린 부분도 괜찮다고 생각합니다!

2024-12-07 17:00 UTC, DaeYoung0726 commented on src/main/java/muzusi/global/response/success/SuccessResponse.java
> +){
다른건 띄어쓰기 되어 있는데 `){`에 띄어쓰기가 없어서 코멘트 남겼습니다 ㅎㅎㅎ
+ CustomException 클래스에도 상속부분에 띄어쓰기가 없어요!

2024-12-07 17:00 UTC, DaeYoung0726 commented on src/main/java/muzusi/global/exception/GlobalExceptionHandler.java
> +    }
저도 전체적인 부분은 보기가 싫고 일부만 보고 싶어서 이러한 로직을 썼었는데, 아래와 같이 로깅을 설정하면 어떨까요?

``` java
logging:
  level:
    root: INFO
    org.springframework: DEBUG
```

그리고, 위와같이 설정하면 applicaiton.yml에서 dev, prod 나누면 좋을 것 같습니다!

2024-12-08 04:30 UTC, hky035 commented on src/main/java/muzusi/global/response/success/SuccessResponse.java
> +){
넵, 해당 부분 확인해서 수정하겠습니다!

앞으로 개발 진행 시에도 유의하겠습니다.

2024-12-08 04:30 UTC, hky035 commented on src/main/java/muzusi/global/response/error/type/CommonErrorType.java
> +public enum CommonErrorType implements BaseErrorType {
저도 type 패키지 안에 모든 에러 타입 클래스를 위치시키는 것이 적절한가에 관한 의문이 있었는데

대영님이 말씀해 주신 것처럼 각 도메인 패키지별 에러 타입을 적용시키는 것이 좋은 방법인 것 같습니다. 감사합니다

2024-12-08 04:31 UTC, hky035 commented on src/main/java/muzusi/global/exception/GlobalExceptionHandler.java
> +    }
넵, 로깅 범위에 관한 논의 및 테스트 진행 후 적용하겠습니다!

StackTrace 출력 부분은 로그 메시지에서 삭제하겠습니다.

2024-12-08 05:58 UTC, DaeYoung0726 approved these changes
고생하셨습니다!

2024-12-08 06:05 UTC, merged